"""Add AI Settings

Revision ID: 09cd22628193
Revises: bc7f3fd943e4
Create Date: 2026-07-16 21:38:56.487381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cd22628193'
down_revision: Union[str, Sequence[str], None] = 'bc7f3fd943e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('default_model', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_id'), 'ai_providers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_providers_provider_name'), 'ai_providers', ['provider_name'], unique=True)
    op.add_column('user_settings', sa.Column('auto_rotate_ai', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('auto_rotate_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'auto_rotate_mode')
    op.drop_column('user_settings', 'auto_rotate_ai')
    op.drop_index(op.f('ix_ai_providers_provider_name'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
