"""Add User and user_id

Revision ID: 61b85a984713
Revises: 457a5f0dcc28
Create Date: 2026-07-16 21:58:13.608533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b85a984713'
down_revision: Union[str, Sequence[str], None] = '457a5f0dcc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_achievements_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ai_providers_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('analytics_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_analytics_activities_date'), ['date'])
        batch_op.create_foreign_key(batch_op.f('fk_analytics_activities_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_daily_summaries_date'), ['date'])
        batch_op.create_foreign_key(batch_op.f('fk_daily_summaries_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_documents_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_knowledge_items_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_missions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_news_items_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_projects_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_quotes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roadmap_edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_roadmap_edges_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_roadmap_nodes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_scholarships_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_study_sessions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_timeline_events_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_universities_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_user_settings_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_xp_logs_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_xp_logs_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_settings_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_universities_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_timeline_events_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_sessions_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scholarships_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roadmap_nodes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('roadmap_edges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roadmap_edges_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quotes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_items_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_missions_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_knowledge_items_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_summaries_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_daily_summaries_date'), type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('analytics_activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_analytics_activities_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_analytics_activities_date'), type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ai_providers_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_achievements_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
