"""Milestone 4 models

Revision ID: bc7f3fd943e4
Revises: a00782364aa3
Create Date: 2026-07-16 21:31:32.947043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7f3fd943e4'
down_revision: Union[str, Sequence[str], None] = 'a00782364aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_id'), 'knowledge_items', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_title'), 'knowledge_items', ['title'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_headline'), 'news_items', ['headline'], unique=False)
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_headline'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_knowledge_items_title'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
